### ISSUE TITLE
Some Cards Not Syncing, Some Disappearing

### ISSUE THREAD

**Issue by lhardie** [w11k/calendar-for-trello#96]
One of my users has been experiencing issues when using Calendar for Trello.  Sometimes cards that were on their calendar have disappeared.  Other times, new cards they have created are not showing up on the calendar.

Before you ask, the cards have due dates, and they are assigned to team members that should appear in the observer view. We have tried the refresh icon many times, and the boards these cards are assigned to are checked off in the list of boards to show on the calendar.

Is it possible that the app is being bogged down by how many boards are being synced to the calendar at once?  (the user is viewing approximately 20 boards on the calendar)

Is it possible that there is a rate limit on the Trello API causing issues with syncing all of their data?

**Comment by CanKattwinkel** [comment]
Hello @lhardie,

actually we are currently investigating a very similar issue of another user (https://github.com/w11k/calendar-for-trello/issues/92).

Right now I have released a new version of the calendar which will print out error messages if the API limit is exhausted. It would be great if you could check if a error messages like this will appear. 

![image](https://cloud.githubusercontent.com/assets/11500619/21349951/0c069206-c6b5-11e6-980e-bdc6c8cca138.png)

Thanks for submitting your issue!


fyi: currently we are developing a [new version](https://w11k.github.io/calendar-for-trello/) of the calendar. But it is still in alpha and we recommend not to use it yet.

**Comment by lhardie** [comment]
Thank you Can.  I assume that on the hosted version, nothing is required in order to start using the new version, other than possibly a browser refresh?

**Comment by lhardie** [comment]
OK, we just got our first error message.  It says "API ERROR Something Went Wrong"

**Comment by lhardie** [comment]
Here is a screencap of the error messages I am seeing in the developer console in Chrome when I see the "API ERROR Something Went Wrong" message.
![trello-cal-error-1](https://cloud.githubusercontent.com/assets/5696599/21440245/40ee32d0-c84f-11e6-9769-f0f07f46f5a5.PNG)

**Comment by lhardie** [comment]
Here is the error message from the developer's console in Chrome.  It appears we are not connecting to the Trello API anymore.
![trello-cal-error-1](https://cloud.githubusercontent.com/assets/5696599/21440443/4809068e-c850-11e6-936d-3ea67a6f1f55.PNG)

**Comment by CanKattwinkel** [comment]
Hey @lhardie, 

we are already on it! Thank you for the detailed information. I'll notify you as soon as the issue is resolved.

Due to the holidays it might take some days..

**Comment by alexander-q** [comment]
Hi guys. I'm getting the above mentioned "to many requests" popup. Is there something we could/should do about it, or should we wait for updates?

**Comment by CanKattwinkel** [comment]
@lhardie @alexander-q 

I've just released a minor update that disables auto refresh for new users of the calendar. Also the loading requests will be delayed a little bit to evade hitting the API limit. 

@lhardie if you still receive `404 // API ERROR Something Went Wrong`, please use the logout function of the calendar to purge all data. Then do a fresh login. I couldn't fully reproduce the issue, but I think it should work now. 

fyi: version 2 of our calendar is just around the corner. We are currently waiting for material 2 to reach a more stable version - since we rely on it for our templating.

**Comment by CanKattwinkel** [comment]
@lhardie @alexander-q 

I've just released a new version of the V2 calendar. If you are using an up to date browser just go ahead and try it: https://w11k.github.io/calendar-for-trello/

The design is not complete and some features may still be missing.

**Comment by studioy** [comment]
@CanKattwinkel Thank you very much.  I logged out and back in on calendar-for-trello.com, and the API error has disappeared for now.

The team member that was experiencing the most problems is on vacation right now, but later this week I should be able to have her do the same thing and confirm for you whether this resolves the issues she has been experiencing.

I have logged in at the V2 location as well and will give it a try.  Thank you for all of your help!

**Comment by alexander-q** [comment]
Hi guys. Tried the V2 link, and I get a screen that looks like this:
![calendar problem](https://cloud.githubusercontent.com/assets/21256562/21625863/c3ffc176-d25d-11e6-839e-dea6fda11aab.png)

Using Chrome 55.0.2883.87 m
Any suggestions?

**Comment by lhardie** [comment]
@CanKattwinkel would it be possible to update the V2 so that the cards show the list and board titles instead of the huge encrypted strings?  I have a team member ready to do some hard testing to see if this version fixes the issue we were experiencing, but without the proper titles it is very hard for her to see which card is which.

**Comment by lhardie** [comment]
@alexander-q have you tried looking in the developer's tools and console to see if you can find any evidence of errors somewhere?

**Comment by CanKattwinkel** [comment]
@lhardie the feature is now implemented and deployed to https://w11k.github.io/calendar-for-trello/

Due to changes on the data, you probably need to logout and login again.



@alexander-q  since it is a beta we cannot provide support at this moment. But feel free to submit the error log from your developers console als lhardie pointed out!

**Comment by alexander-q** [comment]
Hi guys. Here's a shot of the console on my bugged out v2 calendar. Any suggestions?

![image](https://cloud.githubusercontent.com/assets/21256562/21789671/bf1a14c2-d726-11e6-9377-f23f2c157e40.png)

**Comment by lhardie** [comment]
You need to click on the tab labelled "Console" and in there, you should see several error messages (nine of them).  If you can screencap those or copy and paste them, it might help.

 Also, you can look in the tab labelled "network" and check to see if any of the resources the page is trying to fetch are returning 404s or other error codes.

**Comment by alexander-q** [comment]
Hi again. Here's a log:

`EXCEPTION: Cannot read property '56baa0da67b224521195a404' of undefined
ErrorHandler.handleError @ error_handler.js:50
error_handler.js:55ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
error_handler.js:56TypeError: Cannot read property '56baa0da67b224521195a404' of undefined
    at https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:227
    at Array.filter (native)
    at SafeSubscriber._next (https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:33)
    at SafeSubscriber.__tryOrSetError (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1613:16)
    at SafeSubscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1555:27)
    at Subscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1506:26)
    at Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at CombineLatestSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:65209:34)
    at InnerSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:100732:21)
    at InnerSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at DistinctUntilChangedSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:84576:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at MapSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:21244:26)
    at MapSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at SwitchMapSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:109759:30)
ErrorHandler.handleError @ error_handler.js:56
error_handler.js:50EXCEPTION: Cannot read property '56baa0da67b224521195a404' of undefined
ErrorHandler.handleError @ error_handler.js:50
error_handler.js:55ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
error_handler.js:56TypeError: Cannot read property '56baa0da67b224521195a404' of undefined
    at https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:227
    at Array.filter (native)
    at SafeSubscriber._next (https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:33)
    at SafeSubscriber.__tryOrSetError (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1613:16)
    at SafeSubscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1555:27)
    at Subscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1506:26)
    at Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at CombineLatestSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:65209:34)
    at InnerSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:100732:21)
    at InnerSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at DistinctUntilChangedSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:84576:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at MapSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:21244:26)
    at MapSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at SwitchMapSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:109759:30)
ErrorHandler.handleError @ error_handler.js:56
zone.js:407TypeError: Cannot read property '56baa0da67b224521195a404' of undefined
    at https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:227
    at Array.filter (native)
    at SafeSubscriber._next (https://w11k.github.io/calendar-for-trello/main.bundle.js:4451:33)
    at SafeSubscriber.__tryOrSetError (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1613:16)
    at SafeSubscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1555:27)
    at Subscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1506:26)
    at Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at CombineLatestSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:65209:34)
    at InnerSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:100732:21)
    at InnerSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at DistinctUntilChangedSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:84576:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at MapSubscriber._next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:21244:26)
    at MapSubscriber.Subscriber.next (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:1470:18)
    at SwitchMapSubscriber.notifyNext (https://w11k.github.io/calendar-for-trello/vendor.bundle.js:109759:30)`

I can confirm it works on my browser at home, but at work it spits out these errors

**Comment by alexander-q** [comment]
Update: Tried it in Internet Explorer, page doesn't load at all. Tried it in Firefox, got to the initial page, connected to Trello, hit "allow" and I get 404 with this address: https://w11k.github.io/calendar-for-trello/start/setToken#token=3c9f7c0d9fb67ac0153f8dd2bb787ea8b3ca70bd8893026e1a22c1d2418a5719

**Comment by studioy** [comment]
You might need to open a new issue for this... this thread was closed so I'm not sure anyone is seeing it and helping.

**Comment by CanKattwinkel** [comment]
Dont worry - I'm still following the issue! We were just busy with releasing the calendar. You can now access it via [http://calendar-for-trello.com/](http://calendar-for-trello.com). @alexander-q please let me know if you issue is fixed with the latest version. (only running on official version, github link is outdated.)
